[package]
name = "story"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.1.0"
leg = "1.0.0"
serde = "1.0.118"
anyhow = "1.0.37"
serde_json = "1.0.61"
shellexpand = "2.1.0"
dialoguer = "0.7.1"
console = "0.14.0"

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]
