[package]
name = "story"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
async-trait = "0.1.42"
clap = "3.0.0-beta.2"
console = "0.14.0"
dialoguer = "0.7.1"
indicatif = "0.15.0"
serde = "1.0.118"
serde_json = "1.0.61"
shellexpand = "2.1.0"
surf = "2.1.0"
async-std = { version = "1.8.0", features = ["attributes"]}
async-channel = "1.5.1"
