[package]
name = "story"
version = "0.0.1"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
async-trait = "0.1.42"
clap = { version = "3.0.0-beta.2" , features = ["color"] }
console = "0.14.0"
dialoguer = "0.7.1"
indicatif = "0.15.0"
serde = "1.0.118"
serde_json = "1.0.61"
shellexpand = "2.1.0"
surf = "2.1.0"
async-std = { version = "1.8.0", features = ["unstable", "attributes"]}
directories-next = "2.0.0"
futures = "0.3"
colored_json = "2.1.0"
edit = "0.1.2"
ctrlc = "3.1.7"
